# Generated by Django 4.0.6 on 2022-10-01 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='username',
            new_name='autor',
        ),
    ]
