# Generated by Django 4.0.6 on 2022-10-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_publicacion_contenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenpublicacion',
            old_name='imglit',
            new_name='imagen',
        ),
    ]
