# Generated by Django 4.0.6 on 2022-10-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_rename_imglit_imagenpublicacion_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
